modules: hal_silabs: add silabs pearl gecko EFM32PG1B hal
zephyrproject-rtos/hal_silabs pull request #10
Opened 2021-01-04 16:17 UTC by rdmeneze

I added the gecko pearl gecko efm32pg1b hal to the zephyr module.
The correspondent gecko/CMakeLists.txt was changed.

The HAL version is 2.7.8 and I performed tests with target efm32pg_stk3401a

Signed-off-by: Rafael Dias Menezes <rdmeneze@gmail.com>

2021-01-07 09:51 UTC, chrta requested changes
Can you please change your commit message and use https://github.com/zephyrproject-rtos/hal_silabs/pull/7/commits/e85125984bde3887131ccafb1f77638324411fbd as an example?

Otherwise this looks good. `scripts/twister -p efm32pg_stk3401a -b` built all tests successfully.

2021-01-07 09:51 UTC, chrta commented on gecko/CMakeLists.txt
> +
Please remove this empty line.

2021-01-08 10:15 UTC, chrta approved these changes
Thanks, lgtm

2021-01-08 13:20 UTC, galak approved these changes

2021-01-08 13:20 UTC, merged