modules: hal_silabs: Add Silabs Gecko HAL for EFR32BG22 SoCs
zephyrproject-rtos/hal_silabs pull request #13
Opened 2021-05-13 15:26 UTC by sateeshkotapati

Origin: Silicon Labs Gecko SDK
URL:
https://www.silabs.com/products/development-tools/software/simplicity-studio
Version: 3.1.2
Purpose: Add support for Silicon Labs EFR32BG22 SoCs
License: Zlib
Maintained-by: External

Signed-off-by: Sateesh Kotapati <Sateesh.Kotapati@silabs.com>

2021-05-13 15:28 UTC, sateeshkotapati commented
Support added for Silabs' EFR32BG22 SoCs, which I would like to contribute to zephyr

2021-05-13 15:58 UTC, galak commented
Please submit an associated PR on the Zephyr repo that adds SoC and board support that utilizes this.

2021-05-14 14:50 UTC, chrta requested changes
Thank you for your contribution, i just mark this as "Request changes" to block merging. I will do a proper review once the complete code is available, that adds support for this soc to zephyr.

It seems that the board initialization is now used from the service folder. This should be done in a consistent manner for all Silabs EXX32 SoCs (imho).
The README file https://github.com/zephyrproject-rtos/hal_silabs/blob/master/gecko/README should also be adapted to reflect what folders/files need to be copied.

2021-05-17 14:49 UTC, sateeshkotapati commented
I missed gecko/README file in my first commit in this PR. That is updated now.
Board initialization is kept exclusive for EFR32BG22 SoCs and is not extended to all EXX32 devices because validation effort is huge for all the devices.

2021-05-18 12:04 UTC, chrta requested changes
Thank you for the updates. I am ok with keeping the currently supported EXX32 boards as they are now, i agree that it would be a lot of effort. My main points in the comments:

- It seems that my sdk version 3.1.2 i downloaded differs slightly from the code in this pr. This should be fixed/documented.
- Changes applied to the sdk should be done in a separate commit outlining the reasoning for this, e.g. adding a file sl_board_control_config.h. There should be a documentation why this is necessary and how the file was created etc.
- The newly added files in the service folder should be compiled if the SOC selects them and should not depend the SOC define itself. For this new CONFIG_-defines should be added.

2021-05-19 12:36 UTC, sateeshkotapati commented on gecko/CMakeLists.txt
> +zephyr_sources_ifdef(CONFIG_SOC_SERIES_EFR32BG22   common/src/sl_slist.c)
Thank you for the review and detailed comments. I have incorporated all the review comments.

2021-05-19 12:37 UTC, sateeshkotapati commented on gecko/CMakeLists.txt
> +zephyr_sources_ifdef(CONFIG_SOC_GECKO_RTCC         service/sleeptimer/src/sl_sleeptimer.c)
I have incorporated this review comment.

2021-05-19 12:37 UTC, sateeshkotapati commented on gecko/service/sleeptimer/test/main.c
> +#include <stdio.h>
All test directories which are not used are removed.

2021-05-19 12:39 UTC, sateeshkotapati commented on gecko/board/inc/sl_board_control_config.h
> +#ifndef SL_BOARD_CONTROL_CONFIG_H
This file is copied from hardware\board\config directory. This is required as this header file is included in sl_board_init.c file.

2021-05-19 12:39 UTC, sateeshkotapati commented on gecko/board/src/sl_board_init.c
> +/***************************************************************************//**
Updated.

2021-05-19 12:40 UTC, sateeshkotapati commented on gecko/common/inc/sl_status.h
> +/*******************************************************************************
These are necessary as these are used in power_manager files. Updated the files.

2021-05-19 12:40 UTC, sateeshkotapati commented on gecko/Device/SiliconLabs/EFR32BG22/Include/efr32bg22c112f352gm40.h
> + * <b>Copyright 2020 Silicon Laboratories, Inc. www.silabs.com</b>
updated.

2021-05-26 08:02 UTC, chrta commented on gecko/board/inc/sl_board_control_config.h
> +#ifndef SL_BOARD_CONTROL_CONFIG_H
1. Can you document this in the README file -> what to do if a new board is added
2. How does this work if a second board should be supported in a similar way that needs a different config?

2021-05-26 08:07 UTC, chrta requested changes
Thank you for the changes. My open issues:
1. Please document in the README file how the file sl_board_control_config.h is generated, if a new board should be added.
2. How does it work if a second board is added that needs a different sl_board_control_config.h
3. Please squash the commits. I would only expect 2 commits (or maybe only one). One adding the device etc to this repository and a second commit that contains the necessary manual changes/additions.

2021-05-27 08:16 UTC, chrta requested changes
Thank you for the changes, especially the addition to the README file. The only open issue/question i have is:

How does it work if a second board is added that needs a different configuration, i.e. sl_board_control_config.h. I think currently it does not work, but imho it should work.

I would prefer if the generated files would be in different subfolders containing the board name in the path and the build system takes care that the correct files are compiled and inclusion paths are set correctly.

For this one board the current approach might work. But once a second board is added it does not work without manually modifying the generated files in this repository. Imho this is bad.

2021-05-27 08:20 UTC, sateeshkotapati commented
> Thank you for the changes, especially the addition to the README file. The only open issue/question i have is:
> 
> How does it work if a second board is added that needs a different configuration, i.e. sl_board_control_config.h. I think currently it does not work, but imho it should work.
> 
> I would prefer if the generated files would be in different subfolders containing the board name in the path and the build system takes care that the correct files are compiled and inclusion paths are set correctly.
> 
> For this one board the current approach might work. But once a second board is added it does not work without manually modifying the generated files in this repository. Imho this is bad.

I have added the configuration files for all the silabs devices under gecko/board/config. sl_board_control_config.h will be chosen based on the board name that is given in zephyr\boards\arm\efr32_radio\Kconfig.defconfig

2021-05-27 09:25 UTC, chrta commented
> I have added the configuration files for all the silabs devices under gecko/board/config. sl_board_control_config.h will be chosen based on the board name that is given in zephyr\boards\arm\efr32_radio\Kconfig.defconfig

Oh yes, sorry i missed that. I noticed that you modified the board name in https://github.com/zephyrproject-rtos/zephyr/pull/35361/files#diff-e63781934d96e8af747cf94696a9ba7d1f946e4c0113aed1969212d8c4075e35R11 so it does not include the prefix `efr32_radio_` like all the other boards do. I would prefer if It would have the prefix and stripping it is handled in gecko/CMakeLists.txt in a similar way as the cmake variable SILABS_GECKO_DEVICE is created. E.g. including this:

```diff
diff --git a/gecko/CMakeLists.txt b/gecko/CMakeLists.txt
index 731c93c..66f99a3 100644
--- a/gecko/CMakeLists.txt
+++ b/gecko/CMakeLists.txt
@@ -9,6 +9,15 @@
 # respectively.
 string(TOUPPER ${CONFIG_SOC_SERIES} SILABS_GECKO_DEVICE)
 
+# Remove any prefix from the board, e.g. efr32_radio_
+string(FIND ${CONFIG_BOARD} "brd" SILABS_GECKO_BRD_INDEX)
+
+if (${SILABS_GECKO_BRD_INDEX} LESS 0)
+  set(SILABS_GECKO_BOARD ${CONFIG_BOARD})
+else()
+  string(SUBSTRING ${CONFIG_BOARD} ${SILABS_GECKO_BRD_INDEX} -1 SILABS_GECKO_BOARD)
+endif()
+
 set(SILABS_GECKO_PART_NUMBER ${CONFIG_SOC_PART_NUMBER})
 
 zephyr_include_directories(
@@ -28,7 +37,7 @@ zephyr_include_directories(
   service/device_init/config/s2
   service/device_init/config/s2/sdid205
   board/inc
-  board/config/${CONFIG_BOARD}
+  board/config/${SILABS_GECKO_BOARD}
   )
 
 # The gecko SDK uses the cpu name to include the matching device header.
```

This way CONFIG_BOARD for the new boards can include prefixes.
I think for other boards where the config folder name is e.g. gecko/board/config/brd4100a_brd4001a this should be handled in this repository (hal_silabs) by mofifying gecko/CMakeLists.txt and not by modifying CONFIG_BOARD in the main zephyr repository.

2021-05-27 10:06 UTC, chrta approved these changes
Thank you, lgtm

2021-06-10 23:50 UTC, galak commented on gecko/CMakeLists.txt
> +  set(SILABS_GECKO_BOARD "brd4184b")
What is SILABS_GECKO_BOARD used for?

2021-06-24 07:57 UTC, sateeshkotapati commented on gecko/CMakeLists.txt
> +  set(SILABS_GECKO_BOARD "brd4184b")
Sorry for updating late. I missed the notification.
It is used to get board specific configuration from directory "zephyrproject\modules\hal\silabs\gecko\board\config"

2021-06-24 11:54 UTC, galak commented on gecko/CMakeLists.txt
> +  set(SILABS_GECKO_BOARD "brd4184b")
What are you using from board/config/*?

2021-06-24 12:04 UTC, galak commented
Can you split out the code import from any changes/additions as different commits.  So the CMakeLists.txt would be a separate commit for example.

2021-06-24 12:08 UTC, galak requested changes
Would prefer not to import the boards/configs.  I'm also unsure about the services/.  Can we limit the initial import / support to  Device/SiliconLabs/EFR32BG22?

2021-07-14 08:56 UTC, chrta reviewed
I remove my approval until discussion is resolved. Also a lot changed since my last review.

2021-07-20 19:15 UTC, galak commented
Noticed another issue with some of the board/ files is they are not licensed under a license that would be acceptable to the Zephyr project.

https://docs.zephyrproject.org/latest/contribute/external.html#software-license

2022-02-14 08:53 UTC, sateeshkotapati commented
Please review this PR, Thanks

2022-04-20 04:44 UTC, sateeshkotapati commented
Hi Zephyr community, 
Please re-review this PR. I have incorporated all the previous review comments.
Our goal to add more Silabs devices is blocked on this PR. 
Thank you and appreciate your time. 

Regards,
Sateesh

2023-07-27 13:07 UTC, kgugala commented
this PR is deprecated. The changes have been merged in the followup PRs. Closing this one

2023-07-27 13:07 UTC, closed without merging