modules: hal_silabs: Add Silabs Gecko HAL for EFR32BG22C224F512IM40 SoC
zephyrproject-rtos/hal_silabs pull request #19
Opened 2022-09-19 08:50 UTC by lpawelcz

Hi, this PR supersedes https://github.com/zephyrproject-rtos/hal_silabs/pull/13. It is a minimal code that should be added to hal_silabs module in order to get initial support for `EFR32BG22` SoCs. Added code is free of MSLA license which was a problem in https://github.com/zephyrproject-rtos/hal_silabs/pull/13.
Although it is a minimal version of the previous PR, we still need to import code and headers for sleeptimer, power_manager, hfxo_manager together with device_init because we do need all of that for our initial support PR in Zephyr.

Origin: Silicon Labs Gecko SDK
URL:
https://www.silabs.com/products/development-tools/software/simplicity-studio Version: 3.1.2
Purpose: board configuration files are added.
License: Zlib
Maintained-by: External

Co-authored-by: Pawel Czarnecki <pczarnecki@antmicro.com>
Signed-off-by: Sateesh Kotapati <Sateesh.Kotapati@silabs.com>
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>

2022-10-04 08:04 UTC, fkokosinski commented
Hi @chrta @mnkp @galak, sorry for pinging you again, but could you take a look at these changes?

2022-10-13 10:06 UTC, fkokosinski approved these changes

2022-10-28 06:01 UTC, fkokosinski approved these changes
LGTM

2022-11-22 08:42 UTC, sateeshkotapati commented
Please take all the files from GSDK, for e.g., emlib source code and include files) to maintain consistency.

2022-11-30 14:20 UTC, galak requested changes
can you remove the board code.  Any board code should be handled in Zephyr.

2022-12-01 12:09 UTC, lpawelcz commented
> can you remove the board code. Any board code should be handled in Zephyr.

@galak I removed the whole `board` directory. In order to do that I had to create additional [header](https://github.com/zephyrproject-rtos/zephyr/blob/723b591023be47cfecb1e39a2da6b6e225fc56a7/boards/arm/efr32bg_sltb010a/sl_device_init_hfxo_config.h) for defines used in HAL for hfxo initialization in [Zephyr PR](https://github.com/zephyrproject-rtos/zephyr/pull/50352) under board directory. This header is [included](https://github.com/zephyrproject-rtos/hal_silabs/pull/19/files#diff-e1d62ea151c2cec626118ce0399cf6d9e08064d4b6aca929e2dd3f95380a1641R44) in HAL `CMakeLists.txt` through `ZEPHYR_BASE` environment variable. We can see similar solution in [hal_atmel ](https://github.com/zephyrproject-rtos/hal_atmel/blob/master/asf/common/components/wifi/winc1500/CMakeLists.txt#L3).

Please let me know if that change is OK.

2022-12-01 12:38 UTC, kmeinhar commented on gecko/CMakeLists.txt
> +endif()
To me it looks like setting `SILABS_GECKO_BOARD` only effects which `sl_device_init_clocks.c` is compiled in.
To me the content in `brd4184b/sl_device_init_clocks.c` seems to be specific to SoC and not board specific.

We defined a new board which means `${CONFIG_BOARD}` will not be `efr32bg_stlb010a`. That means without altering this `CMakeLists.txt` our project can not compile.

2022-12-01 14:23 UTC, lpawelcz commented on gecko/CMakeLists.txt
> +endif()
Right, I removed the board specific code (`sl_device_init_clocks.c`) from HAL and implemented a separate clock init function in Zephyr PR as part of the board support. Now `SILABS_GECKO_BOARD` is not used anywhere so I deleted it. I believe that, from zephyr perspective, things like clock configuration are specific to given platform, not to whole SoC. That is why I placed the code in board init file.

2022-12-06 16:02 UTC, kmeinhar commented on gecko/CMakeLists.txt
>    )
I think `BOARD_ROOT` is a better fit here. But this variable is a list.
A potential solution could be:
```suggestion
  )
foreach(root ${BOARD_ROOT})
  if(IS_DIRECTORY "${root}/boards/arm/${CONFIG_BOARD}")
    zephyr_include_directories(${root}/boards/arm/${CONFIG_BOARD})
  endif()
endforeach()
```

2022-12-07 09:04 UTC, lpawelcz commented on gecko/CMakeLists.txt
>    )
Right, that will allow us to handle out-of-tree development. Thank you for this, I added the change to the PR.

2022-12-14 09:36 UTC, fkokosinski approved these changes

2022-12-15 14:09 UTC, sateeshkotapati approved these changes
Looks good to me

2022-12-20 10:04 UTC, merged