support EFM32PG22C200F512IM40 SoC
zephyrproject-rtos/hal_silabs pull request #20
Opened 2023-01-24 11:57 UTC by HaimYosefHaim

Hi, to avoid updating the SDK version, I used the same version as in  #19. I just added the relevant files of this SoC.

2023-01-24 12:48 UTC, fkokosinski requested changes
The licensing status of the files in the `gecko/Device/SiliconLabs/EFM32PG22/Source/` is unclear to me, as there are two licenses mentioned in them (MSLA and Zlib). Are these files necessary for the SoC to be properly supported in Zephyr?

2023-01-24 12:48 UTC, fkokosinski commented on gecko/Device/SiliconLabs/EFM32PG22/Source/startup_efm32pg22.c
> +* www.silabs.com/about-us/legal/master-software-license-agreement. This
Note that only OSI-compliant licenses are allowed in Zephyr modules.

2023-01-24 14:41 UTC, HaimYosefHaim commented on gecko/Device/SiliconLabs/EFM32PG22/Source/startup_efm32pg22.c
> +* www.silabs.com/about-us/legal/master-software-license-agreement. This
Sorry. I removed unnecessary for current support in EFM32PG_DK2503A board I want to add

2023-02-01 08:53 UTC, fkokosinski commented
Hi @HaimYosefHaim, thanks for cleaning up the licensing status of this PR.

Usually when changes are made to a Zephyr HAL module repository, there exists an associated PR to the main Zephyr repo, so that maintainers can see how the changes in the HAL repository affect/are used in Zephyr itself. For an example, you could refer to https://github.com/zephyrproject-rtos/zephyr/pull/50352.

It doesn't seem you have created one. Since you are adding support for EFM32PG22 SoCs, I assume you want to add a new board to Zephyr. Could you create a PR in Zephyr, so that I can verify how you are using files provided in this PR?

2024-10-01 09:27 UTC, jerome-pouiller commented
Support for EFM32PG_DK2503A has never been submitted to the Zephyr repo. We can't merge this PR without the associated PR in Zephyr.

2024-10-01 09:27 UTC, closed without merging