modules: hal_silabs: Add support for EFR32BG22C222F352GM40 SoC
zephyrproject-rtos/hal_silabs pull request #36
Opened 2023-08-21 21:38 UTC by wkhadgar

2023-08-22 07:30 UTC, fkokosinski requested changes

2023-08-22 07:30 UTC, fkokosinski commented on gecko/CMakeLists.txt
> +endif()
Please remove this change.

2023-08-22 07:30 UTC, fkokosinski commented on gecko/CMakeLists.txt
> +if (${CONFIG_BOARD} STREQUAL "bgm220pc_22wga2")
This board doesn't seem to be defined anywhere. Could you create a PR to Zephyr that adds it?

2023-08-22 13:46 UTC, wkhadgar reviewed
Removed the end of file change

2023-08-29 07:41 UTC, tgorochowik commented
@wkhadgar all changes in the HAL module require a corresponding PR in the main Zephyr repo that uses this code. So without support for this SoC in the main Zephyr repo we cannot merge this PR

2024-10-01 09:29 UTC, jerome-pouiller commented
Closing because of inactivity.

2024-10-01 09:29 UTC, closed without merging