gecko: EFR32MG24 Device files updated | Update to GSDK 4.3.2
zephyrproject-rtos/hal_silabs pull request #46
Opened 2023-10-31 12:02 UTC by sateeshkotapati

Origin: Silicon Labs Gecko SDK
URL: https://github.com/SiliconLabs/gecko_sdk
Version: 4.3.2
Purpose: Update hal_silabs to gecko_sdk v4.3.2.

Update the EFR32MG24 device files inside `gecko/Device/SiliconLab/EFR32MG24`  from gecko_sdk to align the codebase of hal_silabs with gecko_sdk 4.3.2.

2023-11-08 11:16 UTC, fkokosinski requested changes

2023-11-08 11:16 UTC, fkokosinski commented on gecko/Device/SiliconLabs/EFR32MG24/Source/GCC/efr32mg24.ld
> + * @file     gcc_EFR32MG24.ld
This file won't be used by Zephyr, right? Let's avoid adding files which will not be potentially used by Zephyr.

2023-11-08 11:16 UTC, fkokosinski commented on gecko/Device/SiliconLabs/EFR32MG24/Source/IAR/startup_efr32mg24.s
> +; * # License
Ditto

2023-11-08 11:16 UTC, fkokosinski commented on gecko/Device/SiliconLabs/EFR32MG24/Source/startup_efr32mg24.c
> +* # License
Ditto

2023-11-09 04:26 UTC, sateeshkotapati commented on gecko/Device/SiliconLabs/EFR32MG24/Source/GCC/startup_efr32mg24.S
> + * Agreement (MSLA) available at
Okay, I have removed the mentioned file as it is not necessary.

2023-11-09 04:26 UTC, sateeshkotapati commented on gecko/Device/SiliconLabs/EFR32MG24/Source/GCC/efr32mg24.ld
> + * @file     gcc_EFR32MG24.ld
Removed the file

2023-11-09 04:26 UTC, sateeshkotapati commented on gecko/Device/SiliconLabs/EFR32MG24/Source/IAR/startup_efr32mg24.s
> +; * # License
Removed the file

2023-11-09 04:27 UTC, sateeshkotapati commented on gecko/Device/SiliconLabs/EFR32MG24/Source/startup_efr32mg24.c
> +* # License
Removed the file

2023-11-16 03:57 UTC, sateeshkotapati commented
@fkokosinski, I have done the requested changes, can you please review this again.

2023-11-17 14:01 UTC, fkokosinski approved these changes
LGTM

2023-11-17 14:01 UTC, merged