modules: hal_silabs: Add Proprietary TRX example
zephyrproject-rtos/hal_silabs pull request #49
Opened 2023-12-15 16:04 UTC by zohavas

Add Proprietary TRX example to show SiliconLabs radio board capabilities.

2023-12-22 10:59 UTC, jerome-pouiller requested changes

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +#endif
Wrong indentation. (BTW, I though Zephyr used 4 spaces for indentation)

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_cli.c
> +		shell_fprintf(sh, SHELL_NORMAL, "Received packets: %s\n", "NOK");
I feel this `NOK` statement looks like an error while it is not. I would choose something like `Stop receiving packet` (and `Start receiving packet`).

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_cli.c
> +SHELL_CMD_ARG_REGISTER(info, NULL, "Unique ID of the MCU", cli_info, 1, 0);
You mean "Display unique ID of the MCU" ?

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +static struct gpio_dt_spec led0 = GPIO_DT_SPEC_GET_OR(DT_ALIAS(led0), gpios, {0});
`DT_ALIAS(led0)` or `LED0_NODE`? (BTW, I think definitions of `LED0_NODE` does not bring anything and should be dropped)

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +static const struct gpio_dt_spec button0 = GPIO_DT_SPEC_GET_OR(SW0_NODE, gpios, {0});
Are you sure you need to declare these variables globally?

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +uint8_t init_button(struct gpio_dt_spec button)
You can ceclare this function `static`.

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +#endif
Avoid `#ifdef`. Prefer:
```
    if (DT_NODE_HAS_STATUS(SW1_NODE, okay)) {
        ...
    }
```
(BTW, I suggest to relocate this condition in `init_button()`)

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_cli.c
> +		s_obj.allow_rx = 0;
`allow_rx` is a `bool`.

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +#include "rail_types.h"
You already included this file.

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +		LOG_WRN("Sending is in progress!!!");
Avoid exclamation marks. It clutters the output and does not bring any information.

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +						  .error = seleceted_state};
Space before and after braces.

2023-12-22 10:59 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +	if (RAIL_STATUS_NO_ERROR != status) {
For consistency the code, I suggest to avoid "Yoda notation".  Prefer `status != RAIL_STATUS_NO_ERROR` (In fact, I would even write `if (status)`).

2024-01-08 12:44 UTC, fkokosinski requested changes
Hi! Unfortunately the HAL repo is not the right place to add examples. We should add them in main Zephyr repo instead.

2024-01-08 13:07 UTC, jerome-pouiller commented
> Hi! Unfortunately the HAL repo is not the right place to add examples. We should add them in main Zephyr repo instead.

This exemple only work with Silabs specific API. I don't think it makes sense to place it in Zephyr repo, do you?

However, I believe it makes sense to publish it somewhere. Do you think it should be published on an external repository?

Note Espressif already publish examples with their HAL:
  https://github.com/zephyrproject-rtos/hal_espressif/tree/zephyr/examples

2024-01-08 13:22 UTC, fkokosinski commented
> Note Espressif already publish examples with their HAL: https://github.com/zephyrproject-rtos/hal_espressif/tree/zephyr/examples

Hi! You're right indeed, and we should be fine with hosting these samples here in the SiLabs HAL then :) Thanks for pointing that out.

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/CMakeLists.txt
> +
Please remove these extra spaces at the end of this file.

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/README.rst
> +This application requirers part or board that support RAIL, has radio antenna
```suggestion
This application requires part or board that support RAIL, has radio antenna 
```

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/README.rst
> +about RAIL library version.
```suggestion
about the RAIL library version. 
```

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/README.rst
> +The devices start in receive state.
```suggestion
The devices start in the receiving state.
```

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/prj.conf
> +
Let's remove the options that have been commented out.

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/prj_efr32xg24_dk2601b.conf
> +#CONFIG_STATS_SHELL=y
Ditto

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/src/app_gpio.h
> +#endif /*APP_GPIO_H*/
Let's add a newline character at the end of this file.

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/src/app_process.h
> +#endif
Ditto

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/src/app_rail.c
> +/// Size of RAIL RX/TX FIFO
I understand that this is not an in-tree Zephyr sample, but Zephyr usually disallows for C++ style comments to be used. Can we follow this rule here as well in these examples?

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/src/app_rail.c
> +}
Ditto

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/src/app_rail.h
> +#endif /*APP_RAIL_H*/
Ditto

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/src/config/rail/brd2601b/radio_settings.radioconf
> +</multi_phy_configuration>
Ditto

2024-01-08 13:34 UTC, fkokosinski commented on examples/proprietary_trx/src/config/rail/brd2602a/radio_settings.radioconf
> +</multi_phy_configuration>
Ditto

2024-01-16 07:01 UTC, zohavas commented on examples/proprietary_trx/src/app_rail.c
> +						  .error = seleceted_state};
Zephyr clang-format formatter makes this change.

2024-01-17 15:55 UTC, zohavas commented on examples/proprietary_trx/src/config/rail/brd2601b/radio_settings.radioconf
> +</multi_phy_configuration>
@fkokosinski these are RadioConfigurator phys so user can regenerate any time the rail_config.c and rail_config.h files, I would like to keep them as is.

2024-01-17 15:56 UTC, zohavas commented on examples/proprietary_trx/src/app_rail.c
> +static uint8_t out_packet[TX_PAYLOAD_LENGTH] = {
I would like to keep it as is, as if anybody later would like to modify this during running it would be easier.

2024-01-17 15:58 UTC, zohavas commented on examples/proprietary_trx/src/main.c
> +		}
I understand you opinion, but I would like to stay with state machine with is easier to maintain and extensions. And also it has a cleaner look as well.

2024-01-17 15:58 UTC, zohavas commented on examples/proprietary_trx/src/main.c
> +					    EVENT_CLI_RECEIVE_SETTING | EVENT_RADIO_ERROR),
I would like to stay with this, to make sure that truly only these events will be captured.

2024-01-19 15:31 UTC, jerome-pouiller requested changes

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +	k_event_post(&s_sl_machine.smf_event, EVENT_REQUEST_SEND);
Avoid access to global variable. The usual way to manage that is to declare `struct gpio_callback` as a member of s_sl_machine. Then, use `container_of()` to retrieve a pointer to `s_sl_machine`.

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +	if (led.port && !device_is_ready(led.port)) {
Why don't you use `gpio_is_ready_dt()`?

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +#define RAIL_FIFO_SIZE (128U)
What it is purpose of parentheses?

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +#define TX_PAYLOAD_LENGTH (16U)
Probably you could get rid of this symbol, and use `ARRAY_SIZE(out_packet)` instead.

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +static __ALIGNED(RAIL_FIFO_ALIGNMENT) uint8_t tx_fifo[RAIL_FIFO_SIZE] = {0x00};
No global variables please.

(BTW, initializing file scope variables to 0 is useless).

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +static RAIL_Handle_t rail_handle;
Global variables...

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +
Blank line

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +	// RAIL Rx packet handles
This comment does not bring any information. You can remove it.

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +#ifdef CONFIG_PM
`#ifdef` in the `.c` files clutter the code. I strongly suggest to avoid it. You can relocate the `#ifdef` in the header file. Example: https://github.com/SiliconLabs/wisun-br-linux/blob/main/app_wsbrd/dbus.h

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +	allocated_tx_fifo_size = RAIL_SetTxFifo(rail_handle, tx_fifo, 0, RAIL_FIFO_SIZE);
I assume you can drop `allocated_tx_fifo_size`.

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +	bytes_writen_in_fifo = RAIL_WriteTxFifo(rail_handle, out_data, length, true);
Ditto

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/main.c
> +	struct s_state_machine *s = (struct s_state_machine *)o;
This cast is not needed.

2024-01-19 15:31 UTC, jerome-pouiller commented on examples/proprietary_trx/src/main.c
> +	struct s_state_machine *s = (struct s_state_machine *)o;
Ditto.

2024-01-22 15:14 UTC, zohavas commented on examples/proprietary_trx/src/app_gpio.c
> +static const struct gpio_dt_spec button0 = GPIO_DT_SPEC_GET_OR(SW0_NODE, gpios, {0});
Sorry I misunderstand the first time, bit it is now fixed.

2024-01-23 08:55 UTC, fkokosinski commented on examples/proprietary_trx/src/config/rail/brd2601b/radio_settings.radioconf
> +</multi_phy_configuration>
Makes sense, thanks for the explanation

2024-01-23 09:04 UTC, zohavas commented on examples/proprietary_trx/src/app_rail.h
> +#endif /*APP_RAIL_H*/
I have added to every file, I will double check it! may be the clang script removes it? I will push it up again.

2024-01-23 14:05 UTC, zohavas commented on examples/proprietary_trx/src/autogen/sl_rail_util_callbacks.c
Thank you for pointing these out, I hope with the new GSDK structure these #ifdefs will be removed.

2024-01-23 14:06 UTC, zohavas commented on examples/proprietary_trx/src/app_cli.c
> +// Includes
These are advised from out coding standard and gives a code a good structure and and easier overlook.

2024-01-23 14:10 UTC, zohavas commented on examples/proprietary_trx/src/app_rail.c
> +#define TX_PAYLOAD_LENGTH (16U)
I would like to keep these as a compatibility with the GSDK, so users can easily can make the fifos larger with only one line modification.

2024-01-23 14:26 UTC, jerome-pouiller commented on examples/proprietary_trx/src/main.c
> +		}
I rather think `k_event_wait()` will return several events if several events are queued. The relevant code is in `are_wait_conditions_met()` (`zephyr/kernel/events.c`):
```
static bool are_wait_conditions_met(uint32_t desired, uint32_t current,
				    unsigned int wait_condition)
{
	uint32_t  match = current & desired;

	if (wait_condition == K_EVENT_WAIT_ALL) {
		return match == desired;
	}

	/* wait_condition assumed to be K_EVENT_WAIT_ANY */

	return match != 0;
}
```

2024-01-23 14:28 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +	0x0F, 0x16, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66,
So you mean these values are magic values? I suggest to add a comment that, in this case.

2024-01-23 14:29 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +	0x0F, 0x16, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66,
(explain exactly why we keep that and what are their exact meaning)

2024-01-23 14:37 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_rail.c
> +#define TX_PAYLOAD_LENGTH (16U)
> users can make the fifos larger with only one line modification.

I have to say I rather disagree with that statement. Never write code to be easily modified. Write code to be easily read/understand/debugged.

2024-01-23 15:53 UTC, zohavas commented on examples/proprietary_trx/src/app_cli.c
> +	uint8_t rxForward = (uint8_t)(strtoul(argv[1], NULL, 0));
I have fixed the Camel Case, but I would like to keep the uint8_t.

2024-01-29 14:51 UTC, jerome-pouiller requested changes
Hello @zohavas.

Usually I tried to give all my comments in the two first version of a PR. Unfortunately, some of my comments are still related to code existing since the first version. I am sorry about that, I know it is not convenient.

2024-01-29 14:51 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +static const struct gpio_dt_spec led1 = GPIO_DT_SPEC_GET_OR(DT_ALIAS(led1), gpios, {0});
I believe you can also relocate `led0` and `led1` in `struct s_state_machine`.

2024-01-29 19:43 UTC, jerome-pouiller requested changes

2024-01-29 19:43 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +	const struct gpio_dt_spec button0 = GPIO_DT_SPEC_GET_OR(DT_ALIAS(sw0), gpios, {0});
For uniformity, I would have placed these definitions in `struct s_state_machine`, but it is not a big deal.

2024-01-29 19:43 UTC, jerome-pouiller commented on examples/proprietary_trx/src/main.h
> +struct s_state_machine {
Is the name of this structure still relevant (same for the comment above and the name of the instance below)?

2024-01-29 19:43 UTC, jerome-pouiller commented on examples/proprietary_trx/src/autogen/sl_rail_util_init.c
> +#if SL_RAIL_UTIL_INIT_INST0_ENABLE
I took me a while to understand these symbols are in fact  defined in `hal_silabs/gecko/platform/radio/rail_lib/plugin/rail_util_init/config/proprietary/sl_rail_util_init_inst0_config.h`. I have to admit I believe this choice is confusing for the user. If sl_rail_util_init_inst0_config.h never change, what is the purpose of importing autogen stuff since they will never change? If user should run `slc` to choose options to put in the `sl_rail_util_init_inst0_config.h`, why the file is not a part of the application?

At least we have to carrefuly document that.

2024-01-29 19:43 UTC, jerome-pouiller commented on examples/proprietary_trx/boards/efr32mg22_brd4182a.overlay
> +	cpu-power-states = <&pstate_em1>;
The original code from my intershop was able to support em2 on `brd4182a`, can you check why we can't enable it there?

2024-01-30 11:23 UTC, jerome-pouiller commented on examples/proprietary_trx/boards/efr32mg22_brd4182a.overlay
> +	cpu-power-states = <&pstate_em1>;
My bad, Antoine overloaded the attribute.

2024-01-31 12:27 UTC, zohavas commented on examples/proprietary_trx/src/app_rail.c
> +	*start_of_payload = rx_destination;
This is to be similar with GSDK solution for later use, as for subgiga ieee.15.4, with header the true payload start will be different from the rx_destination

2024-01-31 12:39 UTC, zohavas commented on examples/proprietary_trx/src/app_rail.c
> +	} while (rx_packet_handle != RAIL_RX_PACKET_HANDLE_INVALID);
Tried this solution, seems that RAIL throws RAIL_STATUS_INVALID_CALL , so I will stay with the original solution.

2024-01-31 12:48 UTC, zohavas commented on examples/proprietary_trx/src/autogen/sl_rail_util_init.c
> +#if SL_RAIL_UTIL_INIT_INST0_ENABLE
It was decided with BU and management that these files will be placed there.
I will document it for advanced users.

2024-01-31 14:47 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +	if (DT_NODE_HAS_STATUS(DT_ALIAS(s_state->led1), okay)) {
Are you sure `DT_ALIAS(s_state->led1)` works?

2024-01-31 14:47 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +	if (DT_NODE_HAS_STATUS(DT_ALIAS(s_state->led1), okay)) {
Ditto.

2024-01-31 14:47 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_gpio.c
> +		return EINVAL;
Zephyr tends to return negative values on error: `return -EINVAL;`

2024-01-31 14:47 UTC, jerome-pouiller commented on examples/proprietary_trx/src/app_cli.c
> + * SPDX-License-Identifier: Apache-2.0
Do you think we should add the Silabs Copyright (as in .overlay files)?

2024-02-01 09:47 UTC, zohavas commented on examples/proprietary_trx/src/app_gpio.c
> +	if (DT_NODE_HAS_STATUS(DT_ALIAS(s_state->led1), okay)) {
Accidently was overwritten with mass replace, has been fixed.

2024-02-01 10:07 UTC, jerome-pouiller approved these changes
I am still dubious about the state machine, autogen files, etc...  However, I don't see major issues we could fix without changing the whole design.

2024-02-01 10:18 UTC, zohavas commented
@fkokosinski we are almost ready, we need to validate some things with our legal department. Please wait with the merge until we are ready, thank you.

2024-02-16 11:45 UTC, zohavas commented
@fkokosinski thank you for waiting, we are ready with the requested legal validation, the merge can go, thank you for your help!

2024-02-20 08:10 UTC, fkokosinski commented
> @fkokosinski thank you for waiting, we are ready with the requested legal validation, the merge can go, thank you for your help!

Thanks for the ping. Please note that Zephyr is currently in a feature freeze, meaning we shouldn't be merging anything until it ends on February 23rd. I would also prefer to have 2 ACKs on the PR to Zephyr before moving with this to be sure that these changes will be pulled into Zephyr.

2024-08-29 09:23 UTC, nordicjm requested changes
Samples should not be in hal repositories, this was never agreed with tsc

2024-08-29 09:59 UTC, jhedberg requested changes
> Samples should not be in hal repositories, this was never agreed with tsc

Indeed. I'm trying to find a suitable place where this could potentially land in the main tree, and the closest I've found so far would be under `samples/boards` there.

2024-08-29 09:59 UTC, jhedberg commented on examples/proprietary_trx/README.rst
> +    west build -p always -b efr32bg22_brd4184a
This should IMO include two prior steps:
```
west update hal_silabs
west blobs fetch hal_silabs
```

2025-02-05 16:12 UTC, jerome-pouiller commented
This PR cannot be merged in `hal_silabs` (because it is not the right place), nor in `zephyr` (because it depends on blobs).

However, this PR has been merge in the downstream https://github.com/SiliconLabsSoftware/zephyr-silabs/tree/main/samples/simple_txrx

So, I close this PR.

2025-02-05 16:12 UTC, closed without merging